name: CobbleStoneDropGUI
version: '${project.version}'
main: pl.pomoku.cobblestonedropgui.main.Main
api-version: 1.18
authors: [ HubiRto ]
website: https://github.com/HubiRto
commands:
  drop:
    description: Komenda wyswietlajaca GUI z dropem przedmiotow ze stone'a.
    aliases:
      - d
      - dro
    usage: /<command>
  dodaj:
    usage: /<command> <item>
    description: Komenda przeznaczona dla administacji do dodawania specjalnych blokow.
    aliases:
      - dodawanie
      - dod
      - doda
